### ISSUE TITLE
What settings are you using?

### ISSUE THREAD

**Issue by cinjon** [mayeaux/generate-subtitles#10]
If I use your service with this audio - https://www.gutenberg.org/files/20973/ogg/20973-01.ogg - it captures the entire transcription. If I use it with replicate's default settings (https://replicate.com/openai/whisper), it misses a lot, including the first few sentences. What settings are you using? I'm trying to debug this.
Thanks!

**Comment by mayeaux** [comment]
https://github.com/mayeaux/generate-subtitles/blob/master/transcribe-wrapped.js#L115

You can see here I am just using whatever the user passes in, it depends on the model that you are using probably.
