### ISSUE TITLE
Error npm start | SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by TychoWerner** [mayeaux/generate-subtitles#40]
Both with main and fix-dependencies-issue branch
Ubuntu 22.04 clean Proxmox, whisper, libretranslate, rusttools installed

/root/generate-subtitles/queue/newQueue.js:34
      const matchesByWebsocket = global.jobProcesses[processNumber]?.websocketNumber === websocketNumber;

SyntaxError: Unexpected token '.'
<img width="1006" alt="Scherm­afbeelding 2023-01-06 om 21 44 29" src="https://user-images.githubusercontent.com/34608981/211096807-43c3eb12-1ed2-4397-9f7c-0bce8a115140.png">

**Comment by TychoWerner** [comment]
Seems to be becaused by old nodejs version, ubuntu comes with v12 which does not include the ? operator.
The ?. syntax is called the optional chaining operator, and it was introduced in JavaScript in version ES2020. It allows you to access an object's property only if the object itself is not null or undefined.

It looks like the code you have posted is using this operator, which is not supported in versions of JavaScript prior to ES2020.

To fix the error, you can either update your JavaScript runtime to a version that supports the optional chaining operator (such as Node.js 14 or later), or you can use an alternative method to achieve the same effect.

**Comment by mayeaux** [comment]
Added that you should have Node 14+ in the docs, thanks!
