### ISSUE TITLE
Install on Windows 10

### ISSUE THREAD

**Issue by PiperMp3** [mayeaux/generate-subtitles#51]
Gotten quite close on a Windows platform, but struggling with the last bit.

Error: not found: YoutubeDL

However running "yt-dlp" purely in CMD starts YoutubeDL (so the PATH is correct)
Seems generate-sub code is struggling to find the correct paths or files?

I've dug around in the files, and attempted to add yt-dlp.exe's to several paths 

Thoughts?

**Comment by osb910** [comment]
Hi,
Can you paste the path that you're using in your environment variables?
For me it's like this:
`C:\Python310\Lib\site-packages\yt_dlp`

**Comment by PiperMp3** [comment]
C:\Users\username\generate-subtitles
In here, I got yt-dlp.exe and youtube-dl.exe (added both to be safe)

Reckon it could be an issue to have it within the users location?

**Comment by osb910** [comment]
In this path, you should have `YoutubeDL.py`.

**Comment by PiperMp3** [comment]
Aiight, updated Env Variables,
Moved yt-dlp.exe to `C:\yt-dlp`
I can still invoke yt-dlp via cmd, but `npm start` still errors on Not Found

Unsure what you mean by I should have `YoutubeDL.py` python file, could you elaborate? I have no such file, nor were it within the repo.

**Comment by osb910** [comment]
If not, and you can't add it, try editing the project code as follows:
Go to these two files:
`generate-subtitles/downloading/download.js:9`
and...
`generate-subtitles/downloading/yt-dlp-download.js:11`

then change both lines to this:
`const ytDlpName = 'yt-dlp';`

**Comment by osb910** [comment]
By the way, how did you install ytdlp in the first place? I'm curious because I use Windows for development and I'm the one who suggested the fix that's throwing an error at you.

**Comment by PiperMp3** [comment]
Hello,

Yes so `const ytDlpName = 'yt-dlp';` moved things along for sure.

I forgot to add ffmpeg and that so on to that now.

For yt-dlp I followed `https://github.com/yt-dlp/yt-dlp#release-files` which hands out a .exe.
So pulled that down, and fixed PATH, and bam, worked, so then I moved on to the next part.
Sure there is that other method with python3 and pip, but decided to try it's .exe first.

**Comment by PiperMp3** [comment]
Yea @osb910 - its all running here now, so we all good!

Thank you!

**Comment by osb910** [comment]
Great! You're welcome.

Yeah, that makes sense. I probably followed a different method for installation which doesn't output an .exe at all.
I'll try reinstalling it using this method and then figure out how to support both methods on Windows because what I gave you is just a workaround.

So thank you for your issue.
