### ISSUE TITLE
Futurepedia Embed 

### ISSUE THREAD

**Issue by questionreality** [mayeaux/generate-subtitles#7]
Hey Mayeaux, I'm the founder of Futurepedia - a free directory of 300+ AI tools. 
I had listed your tool on my site a few days ago and it has become really popular on it garnering >35 favourites: https://www.futurepedia.io/tool/free-subtitles-ai 

I'm now releasing a feature that would allow sites to embed their Futurepedia favourite count. You can view an example over here: https://www.webcopilot.co/
If you're interested, please let me know and I can create a pull request.

**Comment by mayeaux** [comment]
I really like your site, for now I am having the frontend be as minimalist as possible, but if I make an About page or something I will add that. Anyways I think your site is great and I see a decent amount of clicks coming from there so thanks a lot and let me get back to when it would be a good time for me to add Futurepedia favourite count
