### ISSUE TITLE
Seems to be stuck at processing screen

### ISSUE THREAD

**Issue by abdcef** [mayeaux/generate-subtitles#9]
![CleanShot 2022-12-13 at 11 31 19](https://user-images.githubusercontent.com/56148250/207219893-a927978a-bfdf-48dc-96d0-357d091a7c4d.png)

Is there a way to track the progress and see how much time is left?

**Comment by abdcef** [comment]
I got this error after a long wait:
![CleanShot 2022-12-13 at 18 18 28](https://user-images.githubusercontent.com/56148250/207291368-f75bb350-29bc-4b57-98d1-b950ff9f921a.png)

**Comment by mayeaux** [comment]
The Vast server I'm using is giving me a lot of issues I will probably end up changing servers
